# Linear algebra with Numpy 🧠🧠

Some practice exercises are available the [Linear Algebra prepwork](https://app.jedha.co/course/linear-algebra-basics/linear-algebra-exercises).
In this exercise, you will apply what you learnt in the "Numpy and Linear Algebra" to check numerically the answers to these exercises.

In [2]:
import numpy as np

## Operations with vectors and matrices 🤹‍♂️🤹‍♂️

### Vector operations

1. Compute the sum $\vec{u} + \vec{v}$ of the following vectors :
$$
\vec{u} =
\begin{bmatrix}
2 \\
9 \\
-1
\end{bmatrix}
$$
$$
\vec{v} =
\begin{bmatrix}
1 \\
5 \\
3
\end{bmatrix}
$$

In [4]:
u = np.array([2, 9, -1])
v = np.array([1, 5, 3])

calc = u + v
print(calc)

[ 3 14  2]


2. Compute the difference $\vec{u} - \vec{v}$ between the following vectors :
$$
\vec{u} =
\begin{bmatrix}
10 \\
-2 \\
1
\end{bmatrix}
$$
$$
\vec{v} =
\begin{bmatrix}
4 \\
3 \\
2
\end{bmatrix}
$$

In [6]:
u = np.array([10, -2, 1])
v = np.array([4, 3, 2])

calc = u - v
print(calc)

[ 6 -5 -1]


3. Compute : $\alpha (\vec{u} + \vec{v})$ with $\alpha = 4$ and :
$$
\vec{u} =
\begin{bmatrix}
1 \\
-2 \\
2
\end{bmatrix}
$$
$$
\vec{v} =
\begin{bmatrix}
2 \\
1 \\
0
\end{bmatrix}
$$

In [8]:
alpha = 4
u = np.array([1, -2, 2])
v = np.array([2, 1, 0])

calc = alpha * (u + v)
print(calc)

[12 -4  8]


4. Compute the norms $\Vert\vec{u}\Vert$ and $\Vert\vec{v}\Vert$ with:
$$
\vec{u}
=
\begin{bmatrix}
1 \\
2 \\
3 \\
4 \\
\end{bmatrix}
$$
$$
\vec{v}
=
\begin{bmatrix}
-1 \\
2 \\
-3 \\
4 \\
\end{bmatrix}
$$

In [10]:
u = np.array([1, 2, 3, 4])
v = np.array([-1, 2, -3, 4])

print("Norm u: ", np.linalg.norm(u))
print("Norm v: ", np.linalg.norm(v))

Norm u:  5.477225575051661
Norm v:  5.477225575051661


### Matrix operations

5. Compute the sum $A + B$ of the two following matrices :
$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
2 & 1 & 4 \\
3 & 4 & 1
\end{bmatrix}
$$
$$
B =
\begin{bmatrix}
2 & 3 & 4 \\
3 & 2 & 5 \\
4 & 5 & 2
\end{bmatrix}
$$

In [12]:
a = np.array([[1, 2, 3], [2, 1, 4], [3, 4, 1]])
b = np.array([[2, 3, 4], [3, 2, 5], [4, 5, 2]])

print(a + b)

[[3 5 7]
 [5 3 9]
 [7 9 3]]


6. Compute the operation $2A - B$ with:
$$
A =
\begin{bmatrix}
1 & 2 & 3 \\
2 & 1 & 4 \\
3 & 4 & 1
\end{bmatrix}
$$
$$
B =
\begin{bmatrix}
2 & 3 & 4 \\
3 & 2 & 5 \\
4 & 5 & 2
\end{bmatrix}
$$

In [23]:
a = np.array([[1, 2, 3], [2, 1, 4], [3, 4, 1]])
b = np.array([[2, 3, 4], [3, 2, 5], [4, 5, 2]])

print(2 * a - b)

[[0 1 2]
 [1 0 3]
 [2 3 0]]


7. Compute the products of matrices : $AB$ and $BA$ with:
$$
A =
\begin{bmatrix}
1 & 0 & 2 \\
2 & 1 & 0 \\
1 & 2 & 1
\end{bmatrix}
$$
$$
B =
\begin{bmatrix}
2 & 0 & 0 \\
1 & 2 & 0 \\
0 & 1 & 2
\end{bmatrix}
$$

AB:
[[2 2 4]
 [5 2 0]
 [4 5 2]]

BA:
[[2 0 4]
 [5 2 2]
 [4 5 2]]


In [47]:
a = np.array([[1, 0, 2], [2, 1, 0], [1, 2, 1]])
b = np.array([[2, 0, 0], [1, 2, 0], [0, 1, 2]])

print("AB:\n", a @ b)
print("AB:\n", a.dot(b))
print("BA:\n", b @ a)
print("BA:\n", b.dot(a))

AB:
 [[2 2 4]
 [5 2 0]
 [4 5 2]]
AB:
 [[2 2 4]
 [5 2 0]
 [4 5 2]]
BA:
 [[2 0 4]
 [5 2 2]
 [4 5 2]]
BA:
 [[2 0 4]
 [5 2 2]
 [4 5 2]]


8. Compute the products of matrices : $AB$ and $BA$ with:
$$
A =
\begin{bmatrix}
1 & 0 \\
2 & 1 \\
1 & 2
\end{bmatrix}
$$
$$
B =
\begin{bmatrix}
2 & 0 & 0 \\
1 & 2 & 0
\end{bmatrix}
$$

AB:
[[2 0 0]
 [5 2 0]
 [4 4 0]]

BA:
[[2 0]
 [5 2]]


In [49]:
a = np.array([[1, 0], [2, 1], [1, 2]])
b = np.array([[2, 0, 0], [1, 2, 0]])

print("AB : \n", a @ b)
print("BA : \n", b @ a)

AB : 
 [[2 0 0]
 [5 2 0]
 [4 4 0]]
BA : 
 [[2 0]
 [5 2]]


### Matrix-vector product

9. Compute the matrix-vector product $A\vec{v}$ with :
$$
A =
\begin{bmatrix}
1 & 0 & 2 \\
2 & 1 & 0 \\
1 & 2 & 1
\end{bmatrix}
$$
$$
\vec{v} =
\begin{bmatrix}
-1 \\
1 \\
2
\end{bmatrix}
$$

[ 3 -1  3]


In [55]:
a = np.array([[1, 0, 2], [2, 1, 0], [1, 2, 1]])
v = np.array([-1, 1, 2])

print(a @ v)

[ 3 -1  3]


## Collinearity and orthogonality 🏌️🏌️

10. Compute the dot product $\vec{u} \cdot \vec{v} $ with:
$$
\vec{u}
=
\begin{bmatrix}
2 \\
-3 \\
-1 \\
\end{bmatrix}
$$
$$
\vec{v}
=
\begin{bmatrix}
3 \\
1 \\
3 \\
\end{bmatrix}
$$

What can you conclude about the angle between the two vectors ?

dot product:  0


In [57]:
u = np.array([2, -3, -1])
v = np.array([3, 1, 3])

print(u.dot(v))

0


11. Are $\vec{u}$, $\vec{v}$ collinear ?
$$
\vec{u}
=
\begin{bmatrix}
4 \\
2 \\
-1
\end{bmatrix}
$$

$$
\vec{v}
=
\begin{bmatrix}
-1 \\
-\frac{1}{2} \\
\frac{1}{4}
\end{bmatrix}
$$

Element-wise division:  [-4. -4. -4.]


In [61]:
u = np.array([4, 2, -1])
v = np.array([-1, -1/2, 1/4])

print(np.cross(u,v))

print(u/v)

[0. 0. 0.]
[-4. -4. -4.]


12. Are $\vec{u}$, $\vec{v}$ and $\vec{w}$ linearly independent (i.e. there's no relationship of multicolinearity between these vectors) ?
$$
\vec{u}
=
\begin{bmatrix}
1 \\
2
\end{bmatrix}
$$

$$
\vec{v}
=
\begin{bmatrix}
-2 \\
1 \\
\end{bmatrix}
$$

$$
\vec{w}
=
\begin{bmatrix}
-1 \\
3
\end{bmatrix}
$$

In [65]:
u = np.array([1, 2])
v = np.array([-2, 1])
w = np.array([-1, 3])

print("u: ", u)
print("w - v:", w - v)

u:  [1 2]
w - v: [1 2]


## Systems of linear equations 🧩🧩

Consider the following system of linear equations :

$$
\begin{equation}
    \begin{cases}
      2x_1 + x_2 = 2\\
      x_1 + 2x_2 + x_3 = 0 \\
      x_2 + 2x_3 = 1
    \end{cases}
\end{equation}
$$

13. We'd like to write the matrix representation of this system of equations, in the form $A\vec{x} = \vec{c}$ where :
- $A$ is a matrix containing the coefficients of the equation
- $\vec{x}$ is the vector of unknowns
- $\vec{c}$ is a vector of constant values

Create a numpy array corresponding to $A$ and another corresponding to $\vec c$

In [67]:
A = np.array([[2, 1, 0], [1, 2, 1], [0, 1, 2]])
c = np.array([2, 0, 1])

14. Use numpy to solve the system of equations

In [ ]:
x = np.lialg.solve(A, c)

Solution: x =  [ 1.75 -1.5   1.25]


In [73]:
x = np.linalg.solve(A, c)
print("Solution: x = ", x)

Solution: x =  [ 1.75 -1.5   1.25]


15. **[Bonus question - for experts only 💪]** Let's use the concept of matrix inverse to solve the system of linear equations !

* Prove that the following matrix is the inverse of matrix $A$ :
$$
B = \begin{bmatrix}
\frac{3}{4} & - \frac{1}{2} & \frac{1}{4} \\
-\frac{1}{2} & 1 & -\frac{1}{2} \\
\frac{1}{4} & -\frac{1}{2} & \frac{3}{4}
\end{bmatrix}
$$

* And then, use $A^{-1}$ to find the solution to the system of equation

Inverse of A: 
[[ 0.75 -0.5   0.25]
 [-0.5   1.   -0.5 ]
 [ 0.25 -0.5   0.75]]

Solution: x =  [ 1.75 -1.5   1.25]


In [99]:
print("Invert A: \n", np.linalg.inv(A))
print("")

B = np.array([[3/4, -1/2, 1/4], [-1/2, 1, -1/2], [1/4, -1/2, 3/4]])

if np.allclose(np.linalg.inv(A), B):
    print("A is the inverse of B")
    print("")


x = np.linalg.solve(A,c)
print(x)

Invert A: 
 [[ 0.75 -0.5   0.25]
 [-0.5   1.   -0.5 ]
 [ 0.25 -0.5   0.75]]

A is the inverse of B

[ 1.75 -1.5   1.25]


## Matrix diagonalization 🤸🤸

15. Consider the following matrix :

$$
A =
\begin{bmatrix}
3 & -1 \\
2 & 0
\end{bmatrix}
$$

a. Show that $\vec{u} = \begin{bmatrix}1\\1\end{bmatrix}$ and $\vec{v} = \begin{bmatrix}1\\2\end{bmatrix}$ are eigenvectors of $A$

b. What are the eigenvalues associated to $\vec{u}$ and $\vec{v}$ ?

Au:  [2 2]
Av:  [1 2]


In [107]:
A = np.array([[3, -1], [2, 0]])
u = np.array([1, 1])
v = np.array([1, 2])

print(A @ u)
print(A @ v)

#Test de eig()
eigenvalues, eigenvectors = np.linalg.eig(A)
print("")

print("Valeurs propres (eigenvalues) :")
print(eigenvalues)

print("\nVecteurs propres (eigenvectors) :")
print(eigenvectors)

[2 2]
[1 2]

Valeurs propres (eigenvalues) :
[2. 1.]

Vecteurs propres (eigenvectors) :
[[0.70710678 0.4472136 ]
 [0.70710678 0.89442719]]


We can notice that:
* $A \vec u = 2 \vec u$ which means that $\vec u$ is an eigenvector of $A$ with eigenvalue 2
* $A \vec v = \vec v$ which means that $\vec u$ is an eigenvector of $A$ with eigenvalue 1.